#!/bin/bash

# ls, sorted by size - help find large files

if [ $# -eq 0 ]
  then
    echo "Usage: $0 [-x] <args>"
    exit 1
fi

# Find the directory this script is running from
# TODO: Not foolproof - use pwd?
my_path=`which $0 `
dir_script_in=`dirname ${my_path}`

# Parse args
POSITIONAL=()
while [[ $# -gt 0 ]]
do
    case $1 in
    -x)
        set -x
        shift
        ;;
    *)  # unknown option - save it in an array for later
        POSITIONAL+=("$1")
        shift
        ;;
    esac
done
set -- "${POSITIONAL[@]}" # restore positional parameters

###### Script starts here

du -s $@ | sort -n
